In [ ]:
import numpy as np

# Creating a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, 15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print the array shape
print("Array shape:", reshaped_array.shape)

# Replace the max in each row by 0
reshaped_array[np.arange(3), np.argmax(reshaped_array, axis=1)] = 0

# Print the modified array
print(reshaped_array)


Array shape: (3, 5)
[[ 8  1 13  0  8]
 [ 0  8  1  8 14]
 [ 4  0  5  5 11]]


In [ ]:
import numpy as np

# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array_2d = np.empty((4, 3), dtype=np.int32)

# Print the shape of the array
print("Shape of the array:", array_2d.shape)

# Print the type of the array
print("Type of the array:", type(array_2d))

# Print the data type of the array
print("Data type of the array:", array_2d.dtype)


Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [ ]:
import numpy as np

# Create the given array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Compute the sum of diagonal elements
diagonal_sum = np.trace(array)

# Print the result
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [7]:
import numpy as np

# a. Create an array of odd and even numbers between 10 to 70
odd_array = np.arange(11, 71, 2)  # Odd numbers from 11 to 71 (inclusive)
even_array = np.arange(10, 71, 2)  # Even numbers from 10 to 70 (inclusive)

print("Odd Array:")
print(odd_array)

print("\nEven Array:")
print(even_array)

# b. Perform at least three element-wise mathematical operations using two arrays of the same size
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Element-wise operations
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

# c. Sort a given array by row and column in ascending order
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sorting by row
sorted_by_row = np.sort(array, axis=1)

# Sorting by column
sorted_by_column = np.sort(array, axis=0)

print("\nSorted by Row:")
print(sorted_by_row)

print("\nSorted by Column:")
print(sorted_by_column)


Odd Array:
[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]

Even Array:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]

Element-wise Addition:
[11 22 33 44 55]

Element-wise Subtraction:
[ -9 -18 -27 -36 -45]

Element-wise Multiplication:
[ 10  40  90 160 250]

Sorted by Row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sorted by Column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [4]:
import numpy as np
import math

# Declare the given array with NaN values
array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

# Check for missing data (NaN) using isnan() function
missing_data = np.isnan(array)

# Print the Boolean output (True for missing data, False for non-missing data)
print(missing_data)


[[False False  True False]
 [False False False False]
 [False  True False  True]]
